import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { Plus } from 'lucide-react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
  active,
  ranking,
  history,
}: {
  children: React.ReactNode
  active: React.ReactNode
  ranking: React.ReactNode
  history: React.ReactNode
}) {
  return (
    <main className="space-y-6 pb-10">
      <header className="flex flex-row items-center gap-4 p-4 py-6">
        <Avatar>
          <AvatarImage src="https://github.com/shadcn.png" />
          <AvatarFallback>CN</AvatarFallback>
        </Avatar>
        <div>
          <strong>Rafael Zoucas</strong>
          <p className="text-muted-foreground text-xs">Ranking #12</p>
        </div>
      </header>

      <div className="flex px-4">
        <Button className="w-full">
          <Plus className="w-4 h-4 mr-2" />
          Novo jogo
        </Button>
      </div>

      <section className="px-4">{active}</section>

      <section className="px-4">{ranking}</section>

      <section className="space-y-3">
        <h1 className="ml-4 font-bold">Últimos jogos</h1>
        {history}
      </section>

      {children}
    </main>
  )
}
